/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registroPasajeros;

import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author cgari
 */
public class ConsultaPuntos extends javax.swing.JDialog {

    //Declaración de las variables de instancia
    private Persona pasajero;
    private boolean confirmacion = false;

    //Constructor 
    public ConsultaPuntos() {

    }

    //Constructor 
    public ConsultaPuntos(javax.swing.JDialog parent, boolean modal, Persona pasajero) {
        super(parent, modal); //Llamado al constructor de la clase padre
        initComponents(); //Carga todo los objetos que halla en el JFrame 
        this.setLocationRelativeTo(null); //Posiciona el JFrame en el centro de la pantalla

        this.txtNombrePunt.setEnabled(false);
        this.txtApellidoPunt.setEnabled(false);
        this.txtPasaportePunt.setEnabled(false);
        this.txtTiquete.setEnabled(false);
        this.txtCantVuelos.setEnabled(false);
        this.txtPuntosAcum.setEnabled(false);
        this.txtPuntosCanjea.setEnabled(false);
        this.txtPuntosDisp.setEnabled(false);

        this.pasajero = pasajero; //Asigna el valor ingresado en el constructor a la variable de instancia       

        cargarDatos(); //Ejecuta el método
    }

    //Método para cargar los datos del objeto personaEditar al formulario
    private void cargarDatos() {

        //Crea un objeto ControlPuntos y lo asigna al objeto Control para inicializarlo con el constructor respectivo
        ControlPuntos control = new ControlPuntos();

        //Asignación de valores de cada variable de instancia del objeto personaEditar a las diferentes opciones del formulario
        this.txtNombrePunt.setText(this.pasajero.getNombre());
        this.txtApellidoPunt.setText(this.pasajero.getApellido());
        this.txtPasaportePunt.setText(this.pasajero.getPasaporte());
        this.txtTiquete.setText(this.pasajero.getNumTiquete());
        this.txtCantVuelos.setText(control.cantidadVuelos(this.pasajero.getPasaporte()));
        this.txtPuntosAcum.setText(control.puntosAcumulados(this.pasajero.getPasaporte()));
        this.txtPuntosCanjea.setText(control.puntosCanjeados(this.pasajero.getPasaporte()));
        this.txtPuntosDisp.setText(control.puntosDisponibles());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCanjearPunt = new javax.swing.JButton();
        btnCancelarPunt = new javax.swing.JButton();
        txtApellidoPunt = new javax.swing.JTextField();
        txtNombrePunt = new javax.swing.JTextField();
        txtPuntosAcum = new javax.swing.JTextField();
        txtTiquete = new javax.swing.JTextField();
        txtPasaportePunt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCantVuelos = new javax.swing.JTextField();
        txtPuntosCanjea = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPuntosDisp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnAceptarPunt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Consulta de Puntos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Apellido:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Número de Pasaporte:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Número de Tiquete:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Puntos acumulados:");

        btnCanjearPunt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCanjearPunt.setText("Canjear");
        btnCanjearPunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanjearPuntActionPerformed(evt);
            }
        });

        btnCancelarPunt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelarPunt.setText("Cancelar");
        btnCancelarPunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPuntActionPerformed(evt);
            }
        });

        txtApellidoPunt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNombrePunt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPuntosAcum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTiquete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPasaportePunt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Cantidad de vuelos:");

        txtCantVuelos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPuntosCanjea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Puntos canjeados:");

        txtPuntosDisp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Puntos disponibles:");

        btnAceptarPunt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAceptarPunt.setText("Aceptar");
        btnAceptarPunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarPuntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(548, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombrePunt)
                            .addComponent(txtApellidoPunt)
                            .addComponent(txtPasaportePunt)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPuntosDisp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPuntosCanjea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPuntosAcum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantVuelos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTiquete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(btnCanjearPunt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnAceptarPunt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnCancelarPunt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel9)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombrePunt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellidoPunt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPasaportePunt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTiquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPuntosAcum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPuntosCanjea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPuntosDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(btnCanjearPunt))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarPunt)
                    .addComponent(btnCancelarPunt))
                .addContainerGap(432, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCanjearPuntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanjearPuntActionPerformed

        //Declaración de variables locales
        int puntosDisp, puntosCanj;

        //Convierte texto de los campos de texto a enteros y los asigna a variables locales
        puntosDisp = Integer.parseInt(this.txtPuntosDisp.getText());
        puntosCanj = Integer.parseInt(this.txtPuntosCanjea.getText());

        //Condicional que se ejecuta en caso de tener menos de 400 puntos
        if (puntosDisp < 400) {
            //Muestra un mensaje en pantalla          
            JOptionPane.showMessageDialog(this,
                    "Puntos insuficientes",
                    "Alto",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            //Condicional que se ejecuta en caso de que el destino indicado por el usuario sea "Panamá"
            if (this.pasajero.getDestino().equals("Panamá")) {
                //Se aplican los puntos
                this.txtPuntosCanjea.setText(Integer.toString(puntosCanj + 400));
                this.txtPuntosDisp.setText(Integer.toString(puntosDisp - 400));
                confirmacion = true; //Registro de que se aplicaron puntos
            } else {
                //Se aplican los puntos
                this.txtPuntosCanjea.setText(Integer.toString(puntosCanj + 500));
                this.txtPuntosDisp.setText(Integer.toString(puntosDisp - 500));
                confirmacion = true; //Registro de que se aplicaron puntos
            }
        }
    }//GEN-LAST:event_btnCanjearPuntActionPerformed

    private void btnCancelarPuntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPuntActionPerformed
        this.setVisible(false); //Se cierra la ventana
    }//GEN-LAST:event_btnCancelarPuntActionPerformed

    private void btnAceptarPuntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarPuntActionPerformed

        //Condicional que se ejecuta en caso de que se hayan aplicados los puntos para registrar la transaccion en el objeto persona
        if (confirmacion == true) {
            this.pasajero.setTipoPago("Puntos");
            this.pasajero.setPuntosCanjeados();
        }

        //Muestra un mensaje en pantalla para indicar que se ingresaron los datos correctamente
        JOptionPane.showMessageDialog(this,
                "Datos ingresados correctamente!",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false); //Se cierra la ventana
    }//GEN-LAST:event_btnAceptarPuntActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarPunt;
    private javax.swing.JButton btnCancelarPunt;
    private javax.swing.JButton btnCanjearPunt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellidoPunt;
    private javax.swing.JTextField txtCantVuelos;
    private javax.swing.JTextField txtNombrePunt;
    private javax.swing.JTextField txtPasaportePunt;
    private javax.swing.JTextField txtPuntosAcum;
    private javax.swing.JTextField txtPuntosCanjea;
    private javax.swing.JTextField txtPuntosDisp;
    private javax.swing.JTextField txtTiquete;
    // End of variables declaration//GEN-END:variables
}
